#pragma kernel Warp

Texture2D<float4> _Input;
RWTexture2D<float4> _Output;
float3x3 _H;

[numthreads(8,8,1)]
void Warp(uint2 id : SV_DispatchThreadID)
{
    uint outW, outH;
    _Output.GetDimensions(outW, outH);

    if (id.x >= outW || id.y >= outH)
        return;

    float3 p = float3(id.x, id.y, 1.0);
    float3 src = mul(_H, p);

    if (abs(src.z) < 1e-6)
    {
        _Output[id] = float4(0,0,0,1);
        return;
    }

    float2 uv = src.xy / src.z;

    uint inW, inH;
    _Input.GetDimensions(inW, inH);

    if (uv.x < 0 || uv.y < 0 || uv.x >= inW || uv.y >= inH)
    {
        _Output[id] = float4(0,0,0,1);
        return;
    }

    _Output[id] = _Input.Load(int3(int2(uv), 0));
}
